const ADD_ERROR_SUCCESS = 'ADD_ERROR_SUCCESS';
const REMOVE_ERROR_SUCCESS = 'REMOVE_ERROR_SUCCESS';
const FORM_IS_SUBMITTED = 'FORM_IS_SUBMITTED';
const ADD_SHOULD_SUBMIT = 'ADD_SHOULD_SUBMIT';
const CHANGE_SHOULD_SUBMIT = 'CHANGE_SHOULD_SUBMIT';
const CLEAR_SHOULD_SUBMIT = 'CLEAR_SHOULD_SUBMIT';
const GET_USER_PROFILE = 'GET_USER_PROFILE';
const SPINNER = 'SPINNER';
const AUTH_USER = 'AUTH_USER';
const UNAUTH_USER = 'UNAUTH_USER';

export {
    ADD_ERROR_SUCCESS,
    REMOVE_ERROR_SUCCESS,
    FORM_IS_SUBMITTED,
    ADD_SHOULD_SUBMIT,
    CHANGE_SHOULD_SUBMIT,
    CLEAR_SHOULD_SUBMIT,
    SPINNER,
    AUTH_USER,
    UNAUTH_USER,
    GET_USER_PROFILE
}

